### ISSUE TITLE
Define and document 4.1 pins 48 through 54

### ISSUE THREAD

**Issue by mciantyre** [mciantyre/teensy4-rs#116]
**Is your feature request related to a problem? Please describe.**
The Teensy 4.1 has additional pins, numbered 48 through 54. They're used to interface external RAM and FLASH. They're not implemented in `teensy4-pins`.

**Describe the solution you'd like**
Implement and document pins 48 through 54 in the `t41` module of `teensy4-pins`.

**Describe alternatives you've considered**
Directly use the `imxrt-iomuxc` APIs, but this requires a deeper understanding of the processor. It's more convenient to use `teensy4-pins`, since that's how the board identifies I/O.

**Additional context**
- This effort resembles #103, which implemented pins 42 through 47.
- [Here's the schematic](https://www.pjrc.com/teensy/schematic41.png). At a quick glance, it's not clear if these pins are documented. The official SDK might have more information.
- Using these new pins for external RAM or FLASH might not work without #86.
- I'm not sure if these pins have any / all of the relevant [`imxrt-iomuxc` pin implementations](https://github.com/imxrt-rs/imxrt-iomuxc). If they're not implemented, that could happen separately.
- Originally requested in #115.

**Comment by Alexander89** [comment]
I'm on it
