### ISSUE TITLE
Configure cache in Rust

### ISSUE THREAD

**Issue by mciantyre** [mciantyre/teensy4-rs#3]
We configure the system caches with a routine written in C (`teensy4-rt/src/cache.c`). The existing routine was taken from the [teensy4 cores repository](https://github.com/PaulStoffregen/cores/blob/master/teensy4/startup.c#L195), since it was the fastest way to integrate the configuration into our runtime library. Reimplement the routine in Rust so that it may be inlined into the startup code, and so that we can remove one more C source.

**Comment by Shock-1** [comment]
Will try and see if i can help

**Comment by mciantyre** [comment]
Closed by #22. Thanks again for the help!
