### ISSUE TITLE
Runtime is unusable without RAL

### ISSUE THREAD

**Issue by mciantyre** [mciantyre/teensy4-rs#4]
Unlike the `cortex-m-rt` runtime crate, which is usable without any other peripheral access crate (PAC), the `teensy4-rt` implicitly depends on the `imxrt-ral` through the `imxrt-hal`. Specifically, it depends on the `imxrt-ral`'s `"rt"` feature, which describes the interrupt table and available interrupt enums. For those familiar with `cortext-m-rt`, it's as if we're always using the `"cortext-m-rt/device"` feature.

Refactor the `teensy4-rt` crate to be usable without the `imxrt-hal` and `imxrt-ral` crates. It will serve value for developers who need a minimal runtime for the Teensy 4, and who also don't want the RAL, HAL, or BSP.

A solution might mimic the behavior of the `cortex-m-rt` crate, which will provide a vector table with all interrupts registered to the default handler. This falls under the umbrella of maintaining compatibility with the `cortex-m-rt` crate.

**Comment by Shock-1** [comment]
where's the teensy4-rt crate?

**Comment by mciantyre** [comment]
It was renamed to `imxrt1062-rt` as part of #17. I updated the issue description and title. Thanks for bringing this up!
