### ISSUE TITLE
`StatefulOutputPin::is_set_high` appears to return incorrect value after calls to `toggle`

### ISSUE THREAD

**Issue by mitchmindtree** [mciantyre/teensy4-rs#67]
I'm currently using pins 3 and 12 to control the `DIRECTION` and `ENABLE` pins on a motor driver respectively. I have a little testing setup where I can submit commands to the teensy via serial by pressing keys, and two of these commands include toggling pins 3 and 12. I'm having teensy log the resulting state of the pins each time it receives a command after it calls `toggle`, however I'm noticing that `is_set_high()` seems to always returns `Ok(false)` after each toggle even though I can see the lead screw in my motor changing rotation directions on each toggle.

I haven't dug any deeper than this yet - one thing that might be worth testing is to see if the same issue occurs when calling `set_high()` and `set_low()` manually rather than `toggle()`.

Also, I'm not yet sure if this is teensy 4.0 specific or if this issue belongs in `imxrt-hal`.

To reproduce:

1. Set pins 3 and 12 as output gpio pins.
2. Call `.toggle().unwrap()`.
3. Print the result of `.is_set_high().unwrap()`.

**Comment by mciantyre** [comment]
Good find! It's a HAL issue. Let's bring the discussion to imxrt-rs/imxrt-rs#70.
