### ISSUE TITLE
Rust-based USB logging

### ISSUE THREAD

**Issue by mciantyre** [mciantyre/teensy4-rs#95]
The [`imxrt-usbd` package](https://github.com/imxrt-rs/imxrt-usbd) provides a USB driver that's compatible with the `usb-device` Rust ecosystem. `imxrt-usbd` should be sufficient to replace the BSP's custom USB stack. Remove the C-based USB driver, and provide a replacement logger that's written in Rust.

The design should not prohibit others from bringing their own USB driver.

**Comment by mciantyre** [comment]
Another way to frame this effort: a [`log` implementation](https://crates.io/crates/log) (or [`defmt` implementation](https://defmt.ferrous-systems.com)) that works with [`usbd-serial`](https://crates.io/crates/usbd-serial). This general package could be a win for other embedded Rust users. I've seen hints of people working on this kind of package in chats and issues, but I haven't found working code. Let me know if you know about something like this.

I'd happily contribute, and integrate it in the BSP. Since it would work beyond this BSP, I would recommend maintaining it elsewhere.

**Comment by brandonros** [comment]
Any docs on how to attach to device and see the `bsp::usb` logs included with template?

**Comment by brandonros** [comment]
```
//! Success criteria: you see log messages when connecting
//! to the Teensy 4 using PuTTY of another serial console.
//! Baud rate is 9600.
```

**Comment by jspngh** [comment]
Hi @mciantyre, this seemed like a nice thing to have so I gave it a shot.
I've mainly borrowed from `imxrt-usbd` + `imxrt-uart-log` and haven't found a way to make it HAL-agnostic yet.
Some feedback and ideas for improvements would be appreciated.
You can find the repo here: https://gitlab.com/jspngh/imxrt-usb-log

**Comment by mciantyre** [comment]
Thanks for giving this a go. It's great to see this support for today's BSP and USB driver. I'll take a look through to see what kind of uses you're considering.

I'm sorry, I've haven't kept this issue up to date. I've been working on [another logging solution](https://github.com/mciantyre/imxrt-hal/tree/master/logging) in [my imxrt-hal fork](https://github.com/mciantyre/imxrt-hal). This other approach requires a whole change in the imxrt-rs ecosystem, so it'll take longer to realize and would only be usable in a future Teensy 4 BSP.

**Comment by jspngh** [comment]
No problem, it looks like a more powerful and flexible solution, I'll keep an eye on your work!
If anything, my attempt served as a learning process.
But maybe someone else finds it useful in the short term, so I wanted to share it.
